### ISSUE TITLE
New taxonomy: most comon protocols

### ISSUE THREAD

**Issue by Rafiot** [MISP/misp-taxonomies#121]

**Comment by Rafiot** [comment]
yes, pretty much

**Comment by SteveClement** [comment]
How would you rate commonality?
/etc/services?
Some magical Shodan or the like ranking?

**Comment by adulau** [comment]
I think those issues were created during the hackathon in Canada and a taxonomy has been done for CCCS https://github.com/MISP/misp-taxonomies/blob/master/cccs/machinetag.json#L700 I'll close the issue. Don't forget to reopen if required.
