### ISSUE TITLE
New taxonomy: Report state

### ISSUE THREAD

**Issue by Rafiot** [MISP/misp-taxonomies#122]
In draft / Release requested / Finalized

**Comment by adulau** [comment]
We can update the workflow taxonomy as we have already a state:

https://github.com/MISP/misp-taxonomies/blob/master/workflow/machinetag.json#L89 

and there is already some other state such review before publication:

https://github.com/MISP/misp-taxonomies/blob/master/workflow/machinetag.json#L31
