### ISSUE TITLE
New taxonomy: Most comon programming languages

### ISSUE THREAD

**Issue by Rafiot** [MISP/misp-taxonomies#123]
Same concept as the protocol names

**Comment by SteveClement** [comment]
What would be the source?

https://insights.stackoverflow.com/survey/2018/

For example?

If there is machine readable data for that we could more easily ingest and keep up to date.

**Comment by adulau** [comment]
I think those issues were created during the hackathon in Canada and a taxonomy has been done for CCCS https://github.com/MISP/misp-taxonomies/blob/master/cccs/machinetag.json#L700 I'll close the issue. Don't forget to reopen if required.

**Comment by Rafiot** [comment]
We may want to have a dedicated taxonomy specially for that.
