### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by deralexxx** [MISP/misp-taxonomies#129]
It would be pretty good to have a license to that repo, other projects having issues using the misp-taxonomies without a propper FOSS lic.

E.g.
https://github.com/google/timesketch/issues/716

Or is there an issue adding a license?

**Comment by joachimmetz** [comment]
This looks like a duplicate of https://github.com/MISP/misp-taxonomies/issues/126. Sry for the additional noise.

**Comment by adulau** [comment]
No worries, I'll close the issue as it was already solved in #126 . (@deralexxx happy holidays ;-)
