### ISSUE TITLE
Disposable domains ?

### ISSUE THREAD

**Issue by cert-lexsi** [MISP/misp-taxonomies#136]
Hi, what do you (all) think is more relevant for disposable email addresses domains ?
i.e.
https://github.com/martenson/disposable-email-domains

A Warninglist or a Taxonomy ?

**Comment by adulau** [comment]
Good catch. I think a warning-list would be great!

**Comment by adulau** [comment]
Thanks for the feedback. It's now part of the default MISP warning-list.
