### ISSUE TITLE
How do you remove a taxonomy?

### ISSUE THREAD

**Issue by infracritical** [MISP/misp-taxonomies#14]
![uscipsectors](https://cloud.githubusercontent.com/assets/11613524/13206592/1f48c44c-d8c7-11e5-801d-360901ae4e96.jpg)
Look at the attach graphic.  When I renamed the taxonomy from "cipsectors" to "uscipsectors", then refreshed the URL, now 2 of the same taxonomy show up.  I've made the change within the "./tools/machinetag.py", as well as the directory name, and the taxonomy name to "uscipsectors".  It still shows 2 of the same thing.

Got any ideas of how to remove the erroneous taxonomy?

**Comment by iglocska** [comment]
Right now there is no clean way of doing it, which is a good point. Looking into it!

**Comment by iglocska** [comment]
We'll be tracking this issue over at MISP/MISP as @rotanid has referenced above.
