### ISSUE TITLE
Typo in `communicate-with-c2-server`

### ISSUE THREAD

**Issue by evandrix** [MISP/misp-taxonomies#149]
There is an extra trailing "n" in the "expanded" field value:
[Capabilities](https://raw.githubusercontent.com/MISP/misp-taxonomies/master/maec-malware-capabilities/machinetag.json)
```
        {
          "value": "communicate-with-c2-server",
          "expanded": "communicate-with-c2-servern"
        },
```

**Comment by evandrix** [comment]
also:
```
        {
          "value": "integrity-violation",
          "expanded": "integrity-violationk"
        },
```

**Comment by adulau** [comment]
Thank you for the report. This has been fixed in https://github.com/MISP/misp-taxonomies/commit/788371461432499007d558fc7acb4477c3d9a898
