### ISSUE TITLE
Diamond model description is wrong

### ISSUE THREAD

**Issue by wesinator** [MISP/misp-taxonomies#172]
The description for the Diamond model introduced in #52 is for the killchain, not the Diamond model. 
https://github.com/MISP/misp-taxonomies/blob/a3be45aa66c606c84790433cb62279b83f18a582/diamond-model/machinetag.json#L4

**Comment by adulau** [comment]
Fixed in #173 Thank you.

**Comment by wesinator** [comment]
Will https://github.com/MISP/misp-taxonomies#diamond-model-for-intrusion-analysis and other references get rebuilt ?
