### ISSUE TITLE
Embedding tag colors in taxonomy definition

### ISSUE THREAD

**Issue by RichieB2B** [MISP/misp-taxonomies#21]
It would be great if the taxonomy definitions would allow for a color code field that would be picked up by MISP. Right now whenever I enable a taxonomy on multiple MISP instances I need to synchronize the tag colors by hand.

**Comment by iglocska** [comment]
That is weird, they should be synchronized. Tag colours depend on the
taxonomy name (colour space) and the tags position within the taxonomy
(gradient).

**Comment by RichieB2B** [comment]
Oh, I see. That is actually not a bad default. In this case my request becomes: ability to choose free form tag colors. Gradients are not always visual distinctive enough.

**Comment by iglocska** [comment]
Yup, it's indeed annoying for massive libraries where the gradients end up
being too close together. I'll look into changing it so that if a colour
value exists in the JSON it will adopt it, otherwise it will stick to the
default behaviour, it's indeed a good point.

**Comment by adulau** [comment]
@iglocska I can propose a colour in the JSON format but it should be set at predicate level and/or value level (as we have some tags without values). We can start with the TLP classification (which is the most important regarding color). Is this fine for you?

**Comment by iglocska** [comment]
Yep, sound good to me.
