### ISSUE TITLE
Image in readme not showing up when using Github with a dark theme

### ISSUE THREAD

**Issue by fhightower** [MISP/misp-taxonomies#210]
When using github with a [dark theme](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-user-account-settings/managing-your-theme-settings), the image in the readme cannot be read.

The image looks like:

<img width="996" alt="Screen Shot 2021-06-21 at 12 50 52" src="https://user-images.githubusercontent.com/3599813/122799097-54375200-d28f-11eb-8e10-3998e509f6f6.png">

**Comment by adulau** [comment]
Lol. It's a transparent background...  I'll make it white. Thanks for the notification.
