### ISSUE TITLE
Add PassiveTotal tags

### ISSUE THREAD

**Issue by elhoim** [MISP/misp-taxonomies#30]
But it will only be meaningful when tags can be added to attributes since they are specific for an IOC/observable:
1. Ever Compromised?  
2. Sinkhole  
3. Classify:Malicious
4. Classify:Suspicious
5. Classify:Non-malicious
6. Classify:Unknown

**Comment by adulau** [comment]
We can create a taxonomy but I'm wondering if PassiveTotal documented all the tags. I have only seen this

https://github.com/passivetotal/python_api/blob/b3e2171842d72b434ef87dc5967acefb435ce0e1/passivetotal/common/const.py

The tags can be also created by users as they wish. Maybe we should ask someone at PassiveTotal. They plan to use the misp-taxonomies too.

**Comment by elhoim** [comment]
The classification are fixed values that can be toggled, for example one amongst Malcious/Suspicious/Non-malicious/Unknown.

Then there is **Ever compromised?** that can be toggled to yes/no.
And **Sinkhole** that can be toggled to yes/no.

All the other ones are indeed user-configurable.

![image](https://cloud.githubusercontent.com/assets/178521/17530686/eaa5a650-5e78-11e6-88a1-f59421785b9f.png)

**Comment by FloatingGhost** [comment]
Implemented in 178faf2 :)

**Comment by Rafiot** [comment]
Closing then!
