### ISSUE TITLE
Mutually exclusive values

### ISSUE THREAD

**Issue by sykaeh** [MISP/misp-taxonomies#35]
It would be nice to be able to say that some values are mutually exclusive. For example, it should not be possible to tag something as "TLP Red" and "TLP Green". This is something that would be good to be able to do for all taxonomies.

**Comment by adulau** [comment]
Indeed, it's a very good and valid point. We have a draft policy format for the taxonomies. The idea is to keep the policy optional for the taxonomies (up to the software or the MISP site admin to enable the enforcing). The policy format parameters would be parameters like "exclusive": True or "exclusive": False.

~~~~
     {
      "colour": "#CC0033",
      "description": "Not for disclosure, restricted to participants only. Sources may use TLP:RED when information cannot be effectively acted upon by additional parties, and could lead to impacts on a party's privacy, reputation, or operations if misused. Recipients may not share TLP:RED information with any parties outside of the specific exchange, meeting, or conversation in which it was originally disclosed. In the context of a meeting, for example, TLP:RED information is limited to those present at the meeting. In most circumstances, TLP:RED should be exchanged verbally or in person.",
      "expanded": "(TLP:RED) Information exclusively and directly given to (a group of) individual recipients. Sharing outside is not legitimate.",
      "value": "red",
      "exclusive": true
     },
     {
      "colour": "#d208f4",
      "expanded": "(TLP:EX:CHR) Information extended with a specific tag called Chatham House Rule (CHR). When this specific CHR tag is mentioned, the attribution (the source of information) must not be disclosed. This additional rule is at the discretion of the initial sender who can decide to apply or not the CHR tag.",
      "value": "ex:chr",
      "exclusive": false
     }
~~~~

We welcome more ideas or feedback on this approach. If this is fine, we will add to the current taxonomies. As far as I know, there is not too much mutually exclusive values except for the classification like TLP or national classification. There are still open issue like mutual exclusive values between namespaces (tlp:white versus NATO classified).

**Comment by adulau** [comment]
We introduced an exclusive flag in MISP taxonomies https://github.com/MISP/misp-taxonomies/commit/f97d3f0339572e3199dd4cb23a43813d7254ac94 and it's also introduced in the Internet-Draft of the format.

https://tools.ietf.org/html/draft-dulaunoy-misp-taxonomy-format-04

Thank you for the initial issue.
