### ISSUE TITLE
Mixed taxonomy level structure & colours of values

### ISSUE THREAD

**Issue by koenigswinter** [MISP/misp-taxonomies#40]
Hi folks,
are the following two taxonomy configurations possible (intended for private taxonomy)?

a) Mixture of "predicate only" and "predicate and value" structure
I receive parsing errors if I ommit the values on "predicate only" level or set the value to "null". However the a unique, not mixed structure "predicate and value" != "null" works fine.

b) Tag colour configuration on "value" level
Like on "predicate" level e. g. in https://github.com/MISP/misp-taxonomies/tree/master/tlp
Colours defined on "value" level are not interpreted in my machinetag.json

**Comment by adulau** [comment]
Hi,

Thank you for your feedback.

(a) and (b) should work. (a) is perfectly valid from a MISP taxonomy standpoint. The parsing errors is from MISP core or PyTaxonomy library? Just to be sure where I can reproduce it.

(b) is an open point on MISP core but I know @iglocska works on it.

Cheers

**Comment by Rafiot** [comment]
@koenigswinter Just to make sue you know about PyTaxonomies: https://github.com/MISP/PyTaxonomies
This python module has 100% support of the taxonomies and should make your life easier.

**Comment by koenigswinter** [comment]
Hi @adulau @Rafiot,
Thank you very much for you quick replies. After creating a completely new "machinetag.json" and using PyTaxonomy, **issue (a) was resolved** :) ! It must have been a JSON format error.
Regarding (b) I defined the colours on the predicate and value level (pls see attachment). However, it is not recognized on predicate (and value level) by MISP core. Could you please take a look, if the defintion is correct? I used https://github.com/MISP/misp-taxonomies/blob/master/tlp/machinetag.json as a template.
Cheers
[machinetag.json.txt](https://github.com/MISP/misp-taxonomies/files/546638/machinetag.json.txt)

**Comment by adulau** [comment]
Colours in tags are supported in MISP. So it should be resolved. Could you check if your issue is still there? and if yes, reopen the issue if required.

Thank you very much.
