### ISSUE TITLE
Text mangled in AccessNow's machine-readable client focuses

### ISSUE THREAD

**Issue by mileswwatkins** [MISP/misp-taxonomies#67]
It looks like there's another client focus (or item from an unrelated collection) mangled into the `description` text of the `Culture` item; I believe the line should read simply `The organization campaigns or acts to promote cultural events`.

https://github.com/MISP/misp-taxonomies/blob/master/accessnow/machinetag.json#L19

**Comment by adulau** [comment]
Nice spot. It's fixed in the new version. Thank you.
