### ISSUE TITLE
New taxonomy - workflow

### ISSUE THREAD

**Issue by adulau** [MISP/misp-taxonomies#78]
workflow:todo="global"

workflow:todo="expansion"
workflow:todo="review"
workflow:todo="review-for-false-positive"
workflow:todo="review-for-publication"

**Comment by RichieB2B** [comment]
Good idea. What is the “global” for?

**Comment by adulau** [comment]
@RichieB2B To have a generic one when the event is incomplete. Maybe I should rename it. Any other ideas?

**Comment by RichieB2B** [comment]
I see. Perhaps name it “incomplete”?

workflow:todo="incomplete”
workflow:todo="add-context”
workflow:todo="check-passive-dns-for-shared-hosting”

**Comment by adulau** [comment]
Thank you for the feedback. I separated todo and state.

First version done in 1baaaa1ee1f70a94ab9064a16ff6da5791d89456. Feedback and updates more than welcome.
